version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: muzo-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - muzo-network
  slskd:
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_USERNAME=maestropolis75
      - SLSKD_SLSK_PASSWORD=Musorga75&
    image: slskd/slskd:latest
    container_name: muzo-slskd
    ports:
      - '5030:5030'
      - '5031:5031'
      - '50300:50300'
    volumes:
      - slskd_app:/app
      - slskd_downloads:/downloads
    restart: unless-stopped
    networks:
      - muzo-network

volumes:
  redis_data:
    driver: local
  slskd_app:
    driver: local
  slskd_downloads:
    driver: local

networks:
  muzo-network:
    driver: bridge
