import { Module } from '@nestjs/common';
import {
  AddTrackToPlaylistUseCase,
  CreatePlaylistUseCase,
  CreateSavedFilterUseCase,
  DeletePlaylistUseCase,
  DeleteSavedFilterUseCase,
  ExportPlaylistToM3UUseCase,
  GetActiveFiltersUseCase,
  GetCurrentFilterUseCase,
  GetFavoriteUseCase,
  GetPlaylistSortingByPlaylistIdUseCase,
  GetPlaylistsStatsUseCase,
  GetPlaylistStatsUseCase,
  GetPlaylistsUseCase,
  GetPlaylistTracksUseCase,
  GetPlaylistTracksWithDetailUseCase,
  GetPlaylistUseCase,
  GetSavedFilterUseCase,
  GetStaticFilterOptionsUseCase,
  RemoveTrackFromPlaylistUseCase,
  UpdatePlaylistTracksPositionsUseCase,
  UpdatePlaylistUseCase,
  UpdateSavedFilterUseCase,
} from './';
import { UpdatePlaylistSortingUseCase } from './playlist-sorting/UpdatePlaylistSorting';

const useCasesProviders = [
  CreatePlaylistUseCase,
  GetPlaylistsUseCase,
  GetPlaylistUseCase,
  UpdatePlaylistUseCase,
  DeletePlaylistUseCase,
  GetPlaylistStatsUseCase,
  GetPlaylistTracksUseCase,
  GetPlaylistsStatsUseCase,
  GetPlaylistSortingByPlaylistIdUseCase,
  GetPlaylistTracksWithDetailUseCase,
  GetFavoriteUseCase,
  AddTrackToPlaylistUseCase,
  RemoveTrackFromPlaylistUseCase,
  ExportPlaylistToM3UUseCase,
  UpdatePlaylistSortingUseCase,
  UpdatePlaylistTracksPositionsUseCase,
  GetStaticFilterOptionsUseCase,
  CreateSavedFilterUseCase,
  GetActiveFiltersUseCase,
  GetSavedFilterUseCase,
  DeleteSavedFilterUseCase,
  UpdateSavedFilterUseCase,
  GetCurrentFilterUseCase,
];
@Module({
  imports: [],
  providers: useCasesProviders,
  exports: useCasesProviders,
})
export class UseCasesModule {}
