import {
	CleanArchPlaylist,
	Playlist,
	PlaylistTrack,
} from '@/__generated__/types';

/** Map CleanArchPlaylist (me.playlists.items) to legacy PlaylistItem shape */
export function toPlaylistItem(item: CleanArchPlaylist): Playlist {
	const s = item.stats;
	const tracks = item.tracks?.map((track) => ({
		__typename: 'PlaylistTrack',
		id: track.id,
		position: track.position,
		addedAt: track.addedAt,
		playlistId: track.playlistId,
		trackId: track.trackId,
		track: {
			__typename: 'SimpleMusicTrack',
			id: track.track.id,
			artist: track.track.artist,
			title: track.track.title,
			duration: track.track.technicalInfo.duration,
			date: track.track.metadata.date,
			isFavorite: track.track.stats.isFavorite,
			isLiked: track.track.stats.isLiked,
			isBanger: track.track.stats.isBanger,
			createdAt: track.track.createdAt,
			updatedAt: track.track.updatedAt,
			tempo: track.track.musicalFeatures.tempo,
			key: track.track.musicalFeatures.key,
			valenceMood: track.track.musicalFeatures.valenceMood,
			arousalMood: track.track.musicalFeatures.arousalMood,
			imagePath: track.track.imagePath,
			lastScannedAt: track.track.lastScannedAt,
			libraryId: track.track.libraryId,
			genres: track.track.metadata.genres,
			subgenres: track.track.metadata.subgenres,
			description: track.track.aiMetadata.description,
			tags: track.track.aiMetadata.tags,
			vocalsDescriptions: track.track.aiMetadata.vocalsDescriptions,
			atmosphereKeywords: track.track.aiMetadata.atmosphereKeywords,
			contextBackgrounds: track.track.aiMetadata.contextBackgrounds,
			contextImpacts: track.track.aiMetadata.contextImpacts,
		},
	}));
	return {
		__typename: 'Playlist',
		id: item.id,
		name: item.name,
		description: item.description ?? undefined,
		createdAt: item.createdAt,
		updatedAt: item.updatedAt,
		bpmRange: s?.bpmRange ?? { __typename: 'Range', min: 0, max: 0 },
		energyRange: s?.energyRange ?? { __typename: 'Range', min: 0, max: 0 },
		genresCount: s?.genresCount ?? 0,
		subgenresCount: s?.subgenresCount ?? 0,
		topGenres: s?.topGenres ?? [],
		topSubgenres: s?.topSubgenres ?? [],
		numberOfTracks: s?.numberOfTracks ?? 0,
		totalDuration: s?.totalDuration ?? 0,
		images: s?.images ?? [],
		isTrackInPlaylist: item.containsTrack ?? false,
		tracks: tracks as PlaylistTrack[],
	};
}
