// Emits the idempotent SQL that seeds the Discogs genre taxonomy, for pasting
// into a migration. Run: npx tsx prisma/scripts/emit-taxonomy-sql.ts
import { flattenTaxonomy } from '../data/discogs-genre-taxonomy';

const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;

const { genres, subgenres } = flattenTaxonomy();

const lines: string[] = [];
lines.push('-- Seed the Discogs `genre_discogs400` taxonomy (genres + styles).');
lines.push('-- Generated by prisma/scripts/emit-taxonomy-sql.ts -- do not edit by hand.');
lines.push('-- Idempotent: ON CONFLICT DO NOTHING leaves existing rows untouched.');
lines.push('');
lines.push('INSERT INTO "genres" ("id", "name") VALUES');
lines.push(genres.map((name) => `  (gen_random_uuid(), ${sqlStr(name)})`).join(',\n'));
lines.push('ON CONFLICT ("name") DO NOTHING;');
lines.push('');
lines.push(
  'INSERT INTO "subgenres" ("id", "name", "genreId")\nSELECT gen_random_uuid(), v.name, g.id\nFROM (VALUES',
);
lines.push(
  [...subgenres]
    .map(([name, parent]) => `  (${sqlStr(name)}, ${sqlStr(parent)})`)
    .join(',\n'),
);
lines.push(') AS v(name, parent)');
lines.push('LEFT JOIN "genres" g ON g.name = v.parent');
lines.push('ON CONFLICT ("name") DO NOTHING;');

console.log(lines.join('\n'));
