import pytest
from loguru import logger


@pytest.fixture(autouse=True)
def test_setup():
    # Remove default loguru handler
    print("Removing default loguru handler")
    logger.remove()

    # Add console handler
    logger.add(
        sink=lambda msg: print(msg, end=""),
        level="DEBUG",
        colorize=True,
        # format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>",
        format="<cyan>{time:YYYY-MM-DD HH:mm:ss}</cyan>| <level>{message}</level>",
    )


@pytest.fixture(scope="session", autouse=True)
def test_audio_files():
    """Test audio files with tempo and key data from the table."""
    return [
        {
            "filename": "/Users/alessandro/Music/ai_test/Celebrai.mp3",
            "tempo": 97.0,
            "key": "E minor",
            "beat_strength": 0.706,
            "tempo_regularity": "high",
            "syncopation": "low",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "bright",
            "valence_mood": "very positive",
            "arousal_mood": "moderate energy",
            "subgenre": "French House",
            "genre": "Dance_EDM",
            "harmonic_metadata": {
                "start_time": 113,
                "duration": 10.0,
                "score": 0.6317733526229858,
            },
            "percussive_metadata": {
                "start_time": 196,
                "duration": 10.0,
                "score": 0.7176162242889405,
            },
            "bpm_metadata": {
                "start_time": 224,
                "duration": 10.0,
                "score": 0.5050284809454577,
            },
            "real_key": "E minor",
            "real_camelot_key": "9A",
            "real_tonnetz_mode": "major",
            "camelot_key": "9A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/D.D. Mirage, Hotel - Exotic Illusions.flac",
            "tempo": 112.3,
            "key": "C major",
            "beat_strength": 0.443,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "neutral",
            "arousal_mood": "calm",
            "subgenre": "Funk",
            "genre": "R&B_Soul",
            "harmonic_metadata": {
                "start_time": 56,
                "duration": 10.0,
                "score": 0.5634070634841919,
            },
            "percussive_metadata": {
                "start_time": 162,
                "duration": 10.0,
                "score": 0.7898473680019379,
            },
            "bpm_metadata": {
                "start_time": 136,
                "duration": 10.0,
                "score": 0.5704762848594606,
            },
            "real_key": "C major",
            "real_camelot_key": "8B",
            "real_tonnetz_mode": "minor",
            "camelot_key": "8B",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/james K - Hypersoft Lovejinx Junkdream.flac",
            "tempo": 161.5,
            "key": "G minor",
            "beat_strength": 0.534,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "energetic",
            "subgenre": "Experimental",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 172,
                "duration": 10.0,
                "score": 0.5593755841255188,
            },
            "percussive_metadata": {
                "start_time": 148,
                "duration": 10.0,
                "score": 0.8218764305114746,
            },
            "bpm_metadata": {
                "start_time": 54,
                "duration": 10.0,
                "score": 0.5577268961625348,
            },
            "real_key": "G minor",
            "real_camelot_key": "6A",
            "real_tonnetz_mode": "major",
            "camelot_key": "6A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/1-2-3 Acid (Jori Hulkkonen Keys of Life Remix).mp3",
            "tempo": 122.3,
            "key": "G major",
            "beat_strength": 0.574,
            "tempo_regularity": "high",
            "syncopation": "low",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "moderate energy",
            "subgenre": "Acid House",
            "genre": "Dance_EDM",
            "harmonic_metadata": {
                "start_time": 194,
                "duration": 10.0,
                "score": 0.6235494613647461,
            },
            "percussive_metadata": {
                "start_time": 112,
                "duration": 10.0,
                "score": 0.8652606725692749,
            },
            "bpm_metadata": {
                "start_time": 112,
                "duration": 10.0,
                "score": 0.5839463934254672,
            },
            "real_key": "G major",
            "real_camelot_key": "9B",
            "real_tonnetz_mode": "minor",
            "camelot_key": "9B",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Alexander Cherdron - Caribbean [Germany] Library, Ambient, Avantgarde, Minimal Synth (1988).mp3",
            "tempo": 95,
            "real_tempo": 119.7,
            "key": "F minor",
            "beat_strength": 0.029,
            "tempo_regularity": "high",
            "bass_presence": "zero",
            "syncopation": "low",
            "danceability_feeling": "slightly-danceable",
            "flatness": "high",
            "spectral_balance": "warm",
            "valence_mood": "neutral",
            "arousal_mood": "very calm",
            "subgenre": "Ambient",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 44,
                "duration": 10.0,
                "score": 0.6243579387664795,
            },
            "percussive_metadata": {
                "start_time": 59,
                "duration": 10.0,
                "score": 0.90625,
            },
            "bpm_metadata": {
                "start_time": 44,
                "duration": 10.0,
                "score": 0.6639045695862758,
            },
            "real_key": "F minor",
            "real_camelot_key": "4A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "4A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Barrington Levy - The Vibes Is Right.flac",
            "tempo": 86.1,
            "key": "A major",
            "beat_strength": 0.033,
            "tempo_regularity": "high",
            "bass_presence": "zero",
            "syncopation": "low",
            "danceability_feeling": "slightly-danceable",
            "flatness": "moderate",
            "spectral_balance": "warm",
            "valence_mood": "negative",
            "arousal_mood": "very calm",
            "subgenre": "Soul",
            "genre": "R&B_Soul",
            "harmonic_metadata": {
                "start_time": 80,
                "duration": 10.0,
                "score": 0.5833571553230286,
            },
            "percussive_metadata": {
                "start_time": 231,
                "duration": 10.0,
                "score": 0.8625,
            },
            "bpm_metadata": {
                "start_time": 131,
                "duration": 10.0,
                "score": 0.5461994909959695,
            },
            "real_key": "A major",
            "real_camelot_key": "11B",
            "real_tonnetz_mode": "minor",
            "camelot_key": "11B",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/C.K - Cough (Transexpress Club Mix).mp3",
            "tempo": 133.9,
            "key": "G# major",
            "beat_strength": 0.844,
            "tempo_regularity": "high",
            "syncopation": "low",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "energetic",
            "subgenre": "Ambient",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 328,
                "duration": 10.0,
                "score": 0.6271390914916992,
            },
            "percussive_metadata": {
                "start_time": 328,
                "duration": 10.0,
                "score": 0.8310874164104461,
            },
            "bpm_metadata": {
                "start_time": 253,
                "duration": 10.0,
                "score": 0.6622659439843949,
            },
            "real_key": "G# major",
            "real_camelot_key": "4B",
            "real_tonnetz_mode": "major",
            "camelot_key": "4B",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Long Island Sound - Gone.flac",
            "tempo": 136.0,
            "key": "D minor",
            "beat_strength": 0.694,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "high",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "energetic",
            "subgenre": "Trance",
            "genre": "Dance_EDM",
            "harmonic_metadata": {
                "start_time": 242,
                "duration": 10.0,
                "score": 0.6091718077659607,
            },
            "percussive_metadata": {
                "start_time": 30,
                "duration": 10.0,
                "score": 0.8292891442775726,
            },
            "bpm_metadata": {
                "start_time": 91,
                "duration": 10.0,
                "score": 0.6477917280217801,
            },
            "real_key": "D minor",
            "real_camelot_key": "7A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "7A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/MJ Nebreda, MS NINA, INVT - Arepa (Explicit).flac",
            "tempo": 89.1,
            "key": "G minor",
            "beat_strength": 0.655,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "negative",
            "arousal_mood": "moderate energy",
            "subgenre": "Dancehall",
            "genre": "Reggae",
            "harmonic_metadata": {
                "start_time": 127,
                "duration": 10.0,
                "score": 0.5629777312278748,
            },
            "percussive_metadata": {
                "start_time": 69,
                "duration": 10.0,
                "score": 0.7341904997825622,
            },
            "bpm_metadata": {
                "start_time": 49,
                "duration": 10.0,
                "score": 0.5314665958088304,
            },
            "real_key": "G minor",
            "real_camelot_key": "6A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "6A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Mark William Lewis - Still Above.flac",
            "tempo": 76.0,
            "key": "A# minor",
            "beat_strength": 0.443,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "low",
            "spectral_balance": "balanced",
            "valence_mood": "neutral",
            "arousal_mood": "calm",
            "subgenre": "Soul",
            "genre": "R&B_Soul",
            "harmonic_metadata": {
                "start_time": 43,
                "duration": 10.0,
                "score": 0.5459762215614319,
            },
            "percussive_metadata": {
                "start_time": 109,
                "duration": 10.0,
                "score": 0.7506531774997711,
            },
            "bpm_metadata": {
                "start_time": 30,
                "duration": 10.0,
                "score": 0.6788860880976072,
            },
            "real_key": "A# minor",
            "real_camelot_key": "3A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "3A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/OCB - Corporate Sound.flac",
            "tempo": 137,
            "real_tempo": 89.1,
            "key": "F minor",
            "beat_strength": 0.163,
            "syncopation": "high",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "moderate",
            "spectral_balance": "bright",
            "valence_mood": "positive",
            "arousal_mood": "calm",
            "subgenre": "Drum'n'bass",
            "genre": "Dance_EDM",
            "harmonic_metadata": {
                "start_time": 55,
                "duration": 10.0,
                "score": 0.5765689015388489,
            },
            "percussive_metadata": {
                "start_time": 55,
                "duration": 10.0,
                "score": 0.7353428423404693,
            },
            "bpm_metadata": {
                "start_time": 180,
                "duration": 10.0,
                "score": 0.5861336133887037,
            },
            "real_key": "F minor",
            "real_camelot_key": "4A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "4A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Rasa - When Will the Day Come.flac",
            "tempo": 98,
            "real_tempo": 95.7,
            "key": "F# minor",
            "beat_strength": 0.036,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "moderately-danceable",
            "flatness": "moderate",
            "spectral_balance": "warm",
            "valence_mood": "negative",
            "arousal_mood": "very calm",
            "subgenre": "Fusion",
            "genre": "Jazz",
            "harmonic_metadata": {
                "start_time": 147,
                "duration": 10.0,
                "score": 0.5837934613227844,
            },
            "percussive_metadata": {
                "start_time": 171,
                "duration": 10.0,
                "score": 0.8014924824237823,
            },
            "bpm_metadata": {
                "start_time": 30,
                "duration": 10.0,
                "score": 0.5295149964984862,
            },
            "real_key": "F# minor",
            "real_camelot_key": "11A",
            "real_tonnetz_mode": "major",
            "camelot_key": "11A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Route 8, Quails - Tomorrow Comes Today.flac",
            "tempo": 107.7,
            "key": "A minor",
            "beat_strength": 0.534,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "neutral",
            "arousal_mood": "calm",
            "subgenre": "Downtempo",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 317,
                "duration": 10.0,
                "score": 0.5789921283721924,
            },
            "percussive_metadata": {
                "start_time": 245,
                "duration": 10.0,
                "score": 0.7623452484607697,
            },
            "bpm_metadata": {
                "start_time": 66,
                "duration": 10.0,
                "score": 0.5122676370601335,
            },
            "real_key": "A minor",
            "real_camelot_key": "8A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "8A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Sam Girling - Post Cause Anthem.flac",
            "tempo": 136.0,
            "key": "A# minor",
            "beat_strength": 0.674,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "bright",
            "valence_mood": "positive",
            "arousal_mood": "energetic",
            "subgenre": "Techno",
            "genre": "Dance_EDM",
            "harmonic_metadata": {
                "start_time": 131,
                "duration": 10.0,
                "score": 0.5767638683319092,
            },
            "percussive_metadata": {"start_time": 30, "duration": 10.0, "score": 0.875},
            "bpm_metadata": {
                "start_time": 151,
                "duration": 10.0,
                "score": 0.6651656972970327,
            },
            "real_key": "A# minor",
            "real_camelot_key": "3A",
            "real_tonnetz_mode": "minor",
            "camelot_key": "3A",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/T-Fire - Say A Prayer.flac",
            "tempo": 136.0,
            "key": "E minor",
            "beat_strength": 0.369,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "warm",
            "valence_mood": "neutral",
            "arousal_mood": "moderate energy",
            "subgenre": "Progressive Rock",
            "genre": "Alternative",
            "harmonic_metadata": {
                "start_time": 254,
                "duration": 10.0,
                "score": 0.6124274730682373,
            },
            "percussive_metadata": {
                "start_time": 209,
                "duration": 10.0,
                "score": 0.81875,
            },
            "bpm_metadata": {
                "start_time": 254,
                "duration": 10.0,
                "score": 0.550626211973681,
            },
            "real_key": "E minor",
            "real_camelot_key": "9A",
            "real_tonnetz_mode": "major",
            "camelot_key": "9A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/UB40 - Kingston Town.flac",
            "tempo": 103.4,
            "key": "G# major",
            "beat_strength": 0.756,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "low",
            "spectral_balance": "bright",
            "valence_mood": "positive",
            "arousal_mood": "energetic",
            "subgenre": "Dub",
            "genre": "Reggae",
            "harmonic_metadata": {
                "start_time": 183,
                "duration": 10.0,
                "score": 0.5478000640869141,
            },
            "percussive_metadata": {
                "start_time": 161,
                "duration": 10.0,
                "score": 0.7773253083229065,
            },
            "bpm_metadata": {
                "start_time": 117,
                "duration": 10.0,
                "score": 0.5989659290986742,
            },
            "real_key": "G# major",
            "real_camelot_key": "4B",
            "real_tonnetz_mode": "major",
            "camelot_key": "4B",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Yes - Tempus Fugit.flac",
            "tempo": 86.1,
            "key": "E minor",
            "beat_strength": 0.518,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "neutral",
            "arousal_mood": "calm",
            "subgenre": "Progressive Rock",
            "genre": "Alternative",
            "harmonic_metadata": {
                "start_time": 188,
                "duration": 10.0,
                "score": 0.590670108795166,
            },
            "percussive_metadata": {
                "start_time": 252,
                "duration": 10.0,
                "score": 0.86875,
            },
            "bpm_metadata": {
                "start_time": 188,
                "duration": 10.0,
                "score": 0.5651955404768485,
            },
            "real_key": "E minor",
            "real_camelot_key": "9A",
            "real_tonnetz_mode": "major",
            "camelot_key": "9A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/🔴 Geoff Bastow - White Lightning 🇬🇧  1976 UK Jazz Funk.mp3",
            "tempo": 97.0,
            "key": "F minor",
            "beat_strength": 0.259,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "zero",
            "danceability_feeling": "slightly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "calm",
            "subgenre": "Contemporary Jazz",
            "genre": "Jazz",
            "harmonic_metadata": {
                "start_time": 113,
                "duration": 10.0,
                "score": 0.6181009411811829,
            },
            "percussive_metadata": {
                "start_time": 97,
                "duration": 10.0,
                "score": 0.8138526618480683,
            },
            "bpm_metadata": {
                "start_time": 47,
                "duration": 10.0,
                "score": 0.5715846084111957,
            },
            "real_key": "F minor",
            "real_camelot_key": "4A",
            "real_tonnetz_mode": "major",
            "camelot_key": "4A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Louisa Miller - Share The Love Around (Dance Mix).mp3",
            "tempo": 83.4,
            "key": "C minor",
            "beat_strength": 0.528,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "high",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "calm",
            "subgenre": "Funk",
            "genre": "R&B_Soul",
            "harmonic_metadata": {
                "start_time": 318,
                "duration": 10.0,
                "score": 0.65149986743927,
            },
            "percussive_metadata": {
                "start_time": 318,
                "duration": 10.0,
                "score": 0.7419099867343902,
            },
            "bpm_metadata": {
                "start_time": 112,
                "duration": 10.0,
                "score": 0.6414803138188975,
            },
            "real_key": "C minor",
            "real_camelot_key": "5A",
            "real_tonnetz_mode": "major",
            "camelot_key": "5A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Index - Волны Будущего.mp3",
            "tempo": 165.4,
            "key": "A minor",
            "beat_strength": 0.713,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "high",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "energetic",
            "subgenre": "New Age",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 135,
                "duration": 10.0,
                "score": 0.6368176341056824,
            },
            "percussive_metadata": {
                "start_time": 162,
                "duration": 10.0,
                "score": 0.7316882252693176,
            },
            "bpm_metadata": {
                "start_time": 162,
                "duration": 10.0,
                "score": 0.7167101811953026,
            },
            "real_key": "C major",
            "real_camelot_key": "8B",
            "real_tonnetz_mode": "major",
            "camelot_key": "8B",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Don Campbell - Tell Me (JA Version).mp3",
            "tempo": 165.4,
            "key": "C minor",
            "beat_strength": 0.626,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "highly-danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "very positive",
            "arousal_mood": "energetic",
            "subgenre": "Gangsta Rap",
            "genre": "Hip-Hop_Rap",
            "harmonic_metadata": {
                "start_time": 125,
                "duration": 10.0,
                "score": 0.6259754300117493,
            },
            "percussive_metadata": {
                "start_time": 220,
                "duration": 10.0,
                "score": 0.644552344083786,
            },
            "bpm_metadata": {
                "start_time": 101,
                "duration": 10.0,
                "score": 0.7687463938965748,
            },
            "real_key": "C major",
            "real_camelot_key": "8B",
            "real_tonnetz_mode": "major",
            "camelot_key": "8B",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/The Solid Doctor - Lights On The Vibe.mp3",
            "tempo": 85.2,
            "key": "Bb major",
            "beat_strength": 0.683,
            "syncopation": "high",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "moderate",
            "spectral_balance": "balanced",
            "valence_mood": "neutral",
            "arousal_mood": "moderate energy",
            "subgenre": "Downtempo",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 126,
                "duration": 10.0,
                "score": 0.6307778358459473,
            },
            "percussive_metadata": {
                "start_time": 270,
                "duration": 10.0,
                "score": 0.6987195491790772,
            },
            "bpm_metadata": {
                "start_time": 174,
                "duration": 10.0,
                "score": 0.6741745399387976,
            },
            "real_key": "E minor",
            "real_camelot_key": "9A",
            "real_tonnetz_mode": "major",
            "camelot_key": "9A",
            "tonnetz_mode": "major",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Midnight Movers, Unltd. - Lost For Words [US] Soul, Funk (1974).mp3",
            "tempo": 85.2,
            "key": "D minor",
            "beat_strength": 0.579,
            "syncopation": "high",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "high",
            "spectral_balance": "balanced",
            "valence_mood": "positive",
            "arousal_mood": "moderate energy",
            "subgenre": "Acid Jazz",
            "genre": "Jazz",
            "harmonic_metadata": {
                "start_time": 143,
                "duration": 10.0,
                "score": 0.6468293070793152,
            },
            "percussive_metadata": {
                "start_time": 188,
                "duration": 10.0,
                "score": 0.86875,
            },
            "bpm_metadata": {
                "start_time": 53,
                "duration": 10.0,
                "score": 0.5826300371317722,
            },
            "real_key": "D major",
            "real_camelot_key": "10B",
            "real_tonnetz_mode": "minor",
            "camelot_key": "10B",
            "tonnetz_mode": "minor",
        },
        {
            "filename": "/Users/alessandro/Music/ai_test/Feel Fly ＂Sole＂ (Extended Versione Tramonto).mp3",
            "tempo": 87.9,
            "key": "G major",
            "beat_strength": 0.366,
            "syncopation": "low",
            "tempo_regularity": "high",
            "bass_presence": "high",
            "danceability_feeling": "danceable",
            "flatness": "high",
            "spectral_balance": "warm",
            "valence_mood": "positive",
            "arousal_mood": "calm",
            "subgenre": "Balearic",
            "genre": "Electronic",
            "harmonic_metadata": {
                "start_time": 30,
                "duration": 10.0,
                "score": 0.6420671939849854,
            },
            "percussive_metadata": {
                "start_time": 204,
                "duration": 10.0,
                "score": 0.8087831139564514,
            },
            "bpm_metadata": {
                "start_time": 378,
                "duration": 10.0,
                "score": 0.6140411591599783,
            },
            "real_key": "B minor",
            "real_camelot_key": "10A",
            "real_tonnetz_mode": "major",
            "camelot_key": "10A",
            "tonnetz_mode": "major",
        },
    ]


@pytest.fixture(scope="session")
def test_low_danceability_files() -> list[dict]:
    """Test audio files with low danceability."""
    return [
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Alex Albreacht - Sunshower.mp3",
            "beat_strength": 0.286,
            "tempo": 108.2,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "G major",
            "camelotKey": "9B",
            "valence": 0.416,
            "valenceMood": "negative",
            "arousal": 0.187,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.7055976360798131,
            "syncopation": 0,
            "acousticness": 0.616,
            "instrumentalness": 0.526,
            "speechiness": 0.039,
            "liveness": 0.68,
            "modeFactor": 0.3,
            "modeConfidence": 0.5297356444708856,
            "modeWeight": 0.07946034667063284,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.1186143243963068,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Aqua.mp3",
            "beat_strength": 0.357,
            "tempo": 133.9,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "A minor",
            "camelotKey": "8A",
            "valence": 0.514,
            "valenceMood": "neutral",
            "arousal": 0.217,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.7393127913071328,
            "syncopation": 0,
            "acousticness": 0.199,
            "instrumentalness": 1,
            "speechiness": 0.08,
            "liveness": 0.71,
            "modeFactor": 0.3,
            "modeConfidence": 0.4883738475827528,
            "modeWeight": 0.07325607713741292,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.3458322088068182,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Ayla - Ayla (Taucher Remix) (1996).mp3",
            "beat_strength": 0.527,
            "tempo": 140.6,
            "danceability": 0,
            "bassPresence": 0,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "F major",
            "camelotKey": "7B",
            "valence": 0.457,
            "valenceMood": "negative",
            "arousal": 0.194,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.6849118417971483,
            "syncopation": 0,
            "acousticness": 0.51,
            "instrumentalness": 0.82,
            "speechiness": 0.04,
            "liveness": 0.63,
            "modeFactor": 0.3,
            "modeConfidence": 0.5311758113796744,
            "modeWeight": 0.07967637170695116,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.1766275745738636,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Constructions Des Temps Modernes - Ace\u0301tal.mp3",
            "beat_strength": 0.019,
            "tempo": 88.2,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "A minor",
            "camelotKey": "8A",
            "valence": 0.35,
            "valenceMood": "negative",
            "arousal": 0.173,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.7524105979959222,
            "syncopation": 0,
            "acousticness": 0.897,
            "instrumentalness": 0.084,
            "speechiness": 0.011,
            "liveness": 0.633,
            "modeFactor": 0.3,
            "modeConfidence": 0.676377836635341,
            "modeWeight": 0.1014566754953011,
            "tempoFactor": 0.5,
            "brightnessFactor": 0,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/DJ ALEPH - Patience Is A Virtue.mp3",
            "beat_strength": 0.781,
            "tempo": 156.2,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "D minor",
            "camelotKey": "7A",
            "valence": 0.453,
            "valenceMood": "negative",
            "arousal": 0.201,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.9,
            "energyFactor": 0.821762489429599,
            "syncopation": 0,
            "acousticness": 0.519,
            "instrumentalness": 0.975,
            "speechiness": 0.015,
            "liveness": 0.607,
            "modeFactor": 0.3,
            "modeConfidence": 0.4982445532187332,
            "modeWeight": 0.07473668298280997,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.1716555841619318,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Dave Brubeck - Golden Brown.mp3",
            "beat_strength": 0.227,
            "tempo": 133.9,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "C# major",
            "camelotKey": "3B",
            "valence": 0.614,
            "valenceMood": "positive",
            "arousal": 0.231,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.6744599924579588,
            "syncopation": 0,
            "acousticness": 0,
            "instrumentalness": 1,
            "speechiness": 0.138,
            "liveness": 0.666,
            "modeFactor": 0.3,
            "modeConfidence": 0.5330409710286614,
            "modeWeight": 0.07995614565429922,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.4795955255681818,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Das Komplex - Jak Moz\u0307na Nie Mo\u0301wic\u0301 O Pesymiz\u0301mie.mp3",
            "beat_strength": 0.591,
            "tempo": 122.3,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "A major",
            "camelotKey": "11B",
            "valence": 0.534,
            "valenceMood": "neutral",
            "arousal": 0.217,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.7804574388066469,
            "syncopation": 0,
            "acousticness": 0.24,
            "instrumentalness": 1,
            "speechiness": 0.072,
            "liveness": 0.623,
            "modeFactor": 0.3,
            "modeConfidence": 0.5429288557038172,
            "modeWeight": 0.08143932835557258,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.32381005859375,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Dominique Guiot - A\u0300 La De\u0301couverte D'Une Amphore.mp3",
            "beat_strength": 0.0,
            "tempo": 187.5,
            "danceability": 0,
            "bassPresence": 0,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "A minor",
            "camelotKey": "8A",
            "valence": 0.487,
            "valenceMood": "neutral",
            "arousal": 0.205,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.745503083793753,
            "syncopation": 0,
            "acousticness": 0.372,
            "instrumentalness": 0.897,
            "speechiness": 0.081,
            "liveness": 0.624,
            "modeFactor": 0.3,
            "modeConfidence": 0.5658820098770487,
            "modeWeight": 0.0848823014815573,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.2517762784090909,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/East-West - Can't Face The Night (Dan Wainwright's Acid Dub Edit).mp3",
            "beat_strength": 0.343,
            "tempo": 122.3,
            "danceability": 0,
            "bassPresence": 1,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "G minor",
            "camelotKey": "6A",
            "valence": 0.608,
            "valenceMood": "positive",
            "arousal": 0.238,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.7475978632604002,
            "syncopation": 0,
            "acousticness": 0.04,
            "instrumentalness": 1,
            "speechiness": 0.116,
            "liveness": 0.719,
            "modeFactor": 0.8,
            "modeConfidence": 0.459600698396863,
            "modeWeight": 0.06894010475952946,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.4326965553977273,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
        {
            "filename": "/Users/alessandro/Music/Youtube/chicco/Enigma - MCMXC a.D - Side 1 (1990 HQ Vinyl Rip) - Technics 1200G \u29f8 Audio Technica ART9.mp3",
            "beat_strength": 0.028,
            "tempo": 152.0,
            "danceability": 0,
            "bassPresence": 0.6680551171302795,
            "tempoRegularity": 0,
            "tempoAppropriateness": 0.8,
            "key": "G# minor",
            "camelotKey": "1A",
            "valence": 0.551,
            "valenceMood": "positive",
            "arousal": 0.223,
            "arousalMood": "very calm",
            "danceabilityFeeling": "experimental",
            "rhythmStability": 0.8,
            "energyFactor": 0.6768254562020616,
            "syncopation": 0,
            "acousticness": 0.223,
            "instrumentalness": 1,
            "speechiness": 0.045,
            "liveness": 0.694,
            "modeFactor": 0.8,
            "modeConfidence": 0.4861033059481323,
            "modeWeight": 0.07291549589221985,
            "tempoFactor": 0.5,
            "brightnessFactor": 0.3329781605113636,
            "harmonicFactor": 0,
            "spectralBalance": 0,
        },
    ]
